# Generated by Django 2.1.5 on 2020-02-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=50)),
                ('product_brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('primary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Primary')),
                ('online_name', models.CharField(max_length=50)),
                ('online_url', models.CharField(max_length=50)),
                ('online_details', models.CharField(max_length=100)),
            ],
            bases=('api.primary',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('primary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Primary')),
                ('person_name', models.CharField(max_length=50)),
                ('person_phone', models.CharField(max_length=13)),
                ('person_details', models.CharField(max_length=100)),
            ],
            bases=('api.primary',),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('primary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Primary')),
                ('shop_name', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=50)),
                ('shop_details', models.CharField(max_length=50)),
            ],
            bases=('api.primary',),
        ),
    ]
